jrocker

diff --git a/jrocker b/jrocker
--- a/jrocker
+++ b/jrocker
@@ -5,6 +5,7 @@ serv=$1
 variable=$2
 port=${variable:-8686}
 
+
 arr[1]='up'
 arr[2]='dn'
 arr[3]='ss'
@@ -47,6 +48,7 @@ function cpf {
 	do
 		name=`basename ${i}`
 		[[ ${name} =~ '.rstudio' ]] && continue
+		[[ ${name} =~ '.vscode' ]] && continue
 		cmd="cp -rf ${i} ${d}/${name}"
 		eval ${cmd}
 	done
@@ -54,7 +56,7 @@ function cpf {
 
 function lnf {
 	d=$1
-	for i in `find /home/liucj -mindepth 1 -prune -type f -name '.*'`;
+	for i in `find ${HOME} -mindepth 1 -prune -type f -name '.*'`;
 	do
 		name=`basename ${i}`
 		[[ ${name} =~ '.rstudio' ]] && continue
@@ -66,39 +68,42 @@ function lnf {
 
 function up {
 
-	cs=(`docker ps|grep -o Jrocker.*$`)
-	[[ ${cs[@]} =~ "Jrocker-${port}" ]] && echo "Error: Jrocker-${port} exists." && exit 1
+	cs=(`docker ps|grep -o ${USER}-rstudio.*$`)
+	[[ ${cs[@]} =~ "${USER}-rstudio-${port}" ]] && echo "Error: ${USER}-rstudio-${port} exists." && exit 1
 
 	[[ ${port} -lt 8686 ]] && echo "Error: New port should be larger than 8686." && exit 1
 
-	jd=/home/liucj/.rstudio-jrocker/Jrocker-${port}
+	jd=${HOME}/.${USER}-rstudio/${USER}-rstudio-${port}
 
 	[[ ! -d ${jd} ]] \
 		&& mkdir -p ${jd} \
 		&& lnf ${jd} \
-		&& ln -s /workspace/liucj ${jd}/data \
-		&& ln -s /project/liucj ${jd}/project
+		&& ln -s /workspace/${USER} ${jd}/data \
+		&& ln -s /project/${USER} ${jd}/project
 
 
 		docker run -d -p ${port}:8787 \
-		-v ${jd}:/home/liucj/ \
-		-v /data/liucj/:/home/liucj/data/ \
-		-v /project/liucj/:/home/liucj/project/ \
-		-v /data/liucj/R/:/home/liucj/R/ \
-		-v /data/liucj/scripts/:/home/liucj/scripts/ \
-		-v /data/liucj/tools/:/home/liucj/tools/ \
-		-e USER=🙃 -e PASSWORD=🙃 \
+		-v ${jd}:${HOME}/ \
+		-v /workspace/${USER}/:${HOME}/workspace/ \
+		-v /project/${USER}/:${HOME}/project/ \
+		-v /data/${USER}/:${HOME}/data/ \
+		-v ${HOME}/R/:${HOME}/R/ \
+		-v ${HOME}/scripts/:${HOME}/scripts/ \
+		-v ${HOME}/tools/:${HOME}/tools/ \
+		-v ${HOME}/github/:${HOME}/github/ \
+		-v ${HOME}/tmp/:${HOME}/tmp/ \
+		-e USER=${USER} -e PASSWORD=u201012670 \
 		-e USERID=$UID -e GROUPID=$GID -e ROOT=TRUE \
-		--name Jrocker-${port} chunjiesamliu/jrocker:latest
+		--name ${USER}-rstudio-${port} chunjiesamliu/jrocker:latest
 
-	echo "Start Jrocker successfully with port ${port}."
+	echo "Start ${USER}-rstudio successfully with port ${port}."
 }
 
 function dn {
-	cs=(`docker ps -a|grep -o Jrocker.*$`)
+	cs=(`docker ps|grep -o ${USER}-rstudio.*$`)
 	if [ ${param} -eq 2 ]
 	then
-		c="Jrocker-${port}"
+		c="${USER}-rstudio-${port}"
 		if [[ ${cs[@]} =~ ${port} ]]
 		then
 			docker container stop ${c}
@@ -106,10 +111,10 @@ function dn {
 			docker container rm ${c}
 			echo "Container ${c} is removed"
 		else
-			echo "Error: Container ${c} not in the docker ps -a"
+			echo "Error: Container ${c} not in the docker ps"
 		fi
 	else
-		echo "Notice: You are going to stop all Jrocker container ${cs[@]}."
+		echo "Notice: You are going to stop all ${USER}-rstudio container ${cs[@]}."
 		echo "Input (yes/no):"
 		read choice
 		case ${choice} in
@@ -124,23 +129,23 @@ function dn {
 				done
 				;;
 			no)
-				echo "No Jrocker container stopped."
+				echo "No ${USER}-rstudio container stopped."
 				;;
 			*)
-				echo "No Jrocker container stopped."
+				echo "No ${USER}-rstudio container stopped."
 				;;
 		esac
 	fi
 }
 
 function ss {
-	info=`docker ps|grep Jrocker`
-	[[ -z ${info} ]] && echo "Notice: no Jrocker container." || docker ps|grep Jrocker
+	info=`docker ps|grep ${USER}-rstudio`
+	[[ -z ${info} ]] && echo "Notice: no ${USER}-rstudio container." || docker ps|grep ${USER}-rstudio
 }
 
 function ex {
-	cs=(`docker ps -a|grep -o Jrocker.*$`)
-	c="Jrocker-${port}"
+	cs=(`docker ps|grep -o ${USER}-rstudio.*$`)
+	c="${USER}-rstudio-${port}"
 	[[ ${param} -ne 2 ]] && echo "Error: Input port for container." && ss && exit 1
 
 	if [[ ${param} -eq 2 && ${cs[@]} =~ ${port} ]]
@@ -148,7 +153,7 @@ function ex {
 		docker exec -it -u $UID:$GID -w ~ ${c} bash
 	else
 		echo "Notice: Input valid jrocker port."
-		docker ps -a|grep Jrocker
+		docker ps|grep ${USER}-rstudio
 	fi
 }
 
